config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/products'

  get 'static_pages/FAQs'
  
  get 'static_pages/index' 

   root 'static_pages#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end

  def products
  end

  def faqs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bikes London</title>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag   'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>
  <body data-stellar-background-ratio="0.5" data-spy="scroll" data-target=".navbar">
    <nav class="navbar navbar-inverse navbar-fixed-top" id="top-bar">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="projectName navbar-brand">
            <%= link_to 'Bikes London', static_pages_index_path %>
          </div><!-- end projectName -->
        </div><!-- end navbar-header -->
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Home', static_pages_index_path %></li>
            <li><%= link_to 'About', static_pages_about_path %></li>
            <li><%= link_to 'Contact', static_pages_contact_path %></li>
            <li><%= link_to 'Products', static_pages_products_path %></li>
            <li><%= link_to 'FAQs', static_pages_FAQs_path %></li>
          </ul><!-- end nav navbar-nav -->
        </div><!-- end navbar-collapse collapse -->
      </div><!-- end container-fluid -->
    </nav><!-- end navbar -->
    <div id="blank">
    </div>

<%= yield %>

    <footer>
      &copy;PJBasa 2016
    </footer>
  </body>
</html>

app/views/static_pages/FAQs.html.erb
<section id="FAQs">
  <div class="title-faqs">
    <h2><strong><u>Frequently Asked Questions</u></strong></h2>
    <p>For any other enquiries, just leave us a message!</p>
  </div>
  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingOne">
        <h4 class="panel-title">
          <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Question #1
          </a>
        </h4> <!-- end panel-title #1 -->
      </div> <!-- end #headingOne -->
      <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
        <div class="panel-body">
           Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam imperdiet eu erat quis elementum. Integer ornare congue nunc. Nullam felis velit, feugiat eget felis at, gravida eleifend orci. Vivamus sed ante facilisis, placerat est nec, hendrerit purus. Praesent venenatis et metus vel sagittis. Nam pulvinar leo lectus, non consequat lectus tempor a. Morbi et luctus purus. Mauris facilisis elementum massa a rutrum. Aliquam sed dignissim tortor. Mauris accumsan felis fringilla dolor porta convallis. Morbi dapibus sit amet arcu non lacinia. Sed lectus lectus, venenatis ac urna et, efficitur dapibus felis. Sed mollis lacus neque, dapibus commodo magna vehicula sed.
        </div> <!-- end panel-body #1 -->
      </div> <!-- end #collapseOne -->
    </div> <!--end panel panel-default collapseOne -->
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingTwo">
        <h4 class="panel-title">
          <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"aria-expanded="false" aria-controls="collapseTwo">
            Question #2
          </a>
        </h4> <!-- end panel-title #2 -->
      </div> <!-- end headingTwo -->
      <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
        <div class="panel-body">
          Proin eleifend erat eget ornare ullamcorper. Nunc sit amet sollicitudin nunc. Fusce dapibus turpis eget orci malesuada pellentesque sit amet sit amet justo. Nunc scelerisque lectus leo, nec hendrerit libero pellentesque ac. Duis nec lacus a elit commodo mattis eget nec lectus. Mauris in tellus vitae diam consequat euismod. Nullam dapibus elit eu libero consectetur consectetur. Donec ut est in odio blandit vestibulum. Duis pretium lectus purus, pulvinar elementum est pellentesque vel. Quisque consequat felis purus, id tristique eros euismod eget. Sed luctus turpis lectus, sit amet porttitor neque auctor vel. Integer metus purus, rhoncus nec risus eget, ullamcorper pharetra lacus. Duis mattis, sem quis consectetur semper, leo nisi volutpat risus, et sagittis tortor ipsum vel dolor. Aliquam a ligula ante. Donec id consectetur nulla. Aenean sit amet ex convallis, condimentum arcu ut, luctus lacus.
        </div> <!-- end panel-body #2 -->
      </div> <!-- end #collapseTwo -->
    </div> <!--end panel panel-default #2 -->
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="headingThree">
          <h4 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
              Question #3
            </a>
          </h4> <!-- end panel-title #3 -->
        </div> <!-- end headingThree -->
        <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
          <div class="panel-body">
            Praesent eu lectus tincidunt, tristique orci vitae, consectetur magna. Donec ac ante nisl. Aenean id lacinia magna, ut placerat urna. Vestibulum efficitur elit nec gravida aliquet. Vestibulum quis magna quis lorem sollicitudin bibendum. Quisque non vehicula tellus. Praesent dictum, mauris id commodo commodo, massa justo egestas purus, at maximus ipsum felis eget sapien. Sed egestas egestas nisi. Nulla facilisi. Nullam vitae feugiat dui. Etiam tellus mi, gravida ac pharetra id, laoreet eget velit. Nullam vitae velit eget nibh rhoncus ornare at ac libero. Donec massa odio, semper quis nisl non, pharetra viverra enim. Cras nec dapibus mauris.
          </div> <!-- end panel-body #3 -->
        </div> <!-- end collapseThree -->
      </div> <!-- end panel panel-default #3 -->
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="headingFour">
          <h4 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
              Question #4
            </a>
          </h4> <!-- end panel-title #4 -->
        </div> <!-- end panel-heading #4 -->
        <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
          <div class="panel-body">
            Etiam pulvinar libero finibus commodo suscipit. Pellentesque fringilla ex vitae ligula consequat, vitae posuere felis sodales. Praesent at dolor sagittis, lacinia lorem sed, ultrices mauris. Phasellus gravida turpis eu urna facilisis lobortis. Morbi non tortor ante. Fusce ultricies cursus laoreet. Sed placerat velit sed risus dictum placerat. Etiam sit amet accumsan enim. Curabitur eu finibus mauris, ut pretium felis. Vivamus finibus rutrum luctus. Aenean blandit nisl eget hendrerit tincidunt. Sed ligula erat, dignissim eu eros at, tincidunt tristique magna. Praesent sed urna et augue pretium mollis. Phasellus sit amet arcu sit amet neque iaculis venenatis. Sed risus lectus, imperdiet in purus ut, sollicitudin venenatis mi.
          </div> <!-- end panel-body #4 -->
        </div> <!-- end collapseFour -->
      </div> <!-- end panel panel-default #4 -->
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="headingFive">
          <h4 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
              Question #5
            </a>
          </h4> <!-- end panel-title #5 -->
        </div> <!-- panel-heading #5 -->
        <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
          <div class="panel-body">
            Sed ut dolor in elit accumsan tempus vitae eu diam. Donec aliquet ante quis lobortis volutpat. Vivamus eget magna maximus, semper augue eu, porttitor justo. Sed lorem metus, cursus sed pharetra sed, convallis vel lectus. Nullam sagittis velit non quam tincidunt bibendum nec vel justo. Aenean eget pellentesque est. Nullam vel augue molestie, laoreet nulla et, laoreet libero. Mauris lobortis mi nec sapien accumsan hendrerit. Cras et libero imperdiet, vehicula augue a, ornare massa. Quisque porttitor commodo magna, a consequat augue varius molestie. Mauris finibus neque vitae quam hendrerit, sit amet feugiat odio eleifend. Mauris placerat mauris vitae vestibulum convallis. Integer in nulla felis. Morbi molestie pharetra orci sit amet sodales. Etiam vehicula aliquam purus, ut consectetur purus hendrerit sit amet.
          </div> <!-- end panel-body #5 -->
        </div> <!-- end collapseFive -->
      </div> <!-- and panel panel-default #5 -->
    </div> <!-- end #accordion -->
</section>

app/views/static_pages/about.html.erb
<section id="about">
  <h1>About Bikes London</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nisi arcu, viverra non facilisis vitae, euismod quis elit. Ut lacinia egestas elementum. Phasellus laoreet ligula at sem tincidunt, commodo mattis ligula pulvinar. Praesent interdum, tortor et eleifend semper, risus arcu vehicula massa, sed porta libero nulla a felis. Vivamus varius leo in odio congue, sit amet euismod massa consectetur. Maecenas iaculis ante et luctus volutpat. Integer lacus purus, scelerisque ut auctor sit amet, volutpat tincidunt turpis. Nullam nec accumsan mi.</p>
  <br>

  <%=image_tag("shop1.jpg", class: "img-responsive", align: "center", id: "about-photo1")%>
  <p>This is Bikes London folding bicycles section.</p>

  <br>
 
  <p>Fusce id nunc ac quam rutrum ullamcorper eu non augue. Nulla varius, mi in porta fringilla, sem mauris iaculis metus, ac feugiat nibh neque at dui. Maecenas commodo semper elementum. Sed libero elit, rhoncus malesuada consequat eleifend, posuere id magna. Nulla purus nisl, vestibulum sed lectus eu, mattis luctus urna. Nunc pretium dignissim ex, vitae cursus velit dapibus quis. Sed in sapien ut tortor ultrices accumsan. Nam tristique lorem id elit pulvinar finibus. Fusce ac interdum libero. Quisque et finibus nulla. Nam porttitor blandit ullamcorper. Donec vulputate vehicula volutpat.</p><br>

  <p>Nunc vitae dictum ex. Aliquam tempor, nunc sed dignissim dignissim, eros felis elementum urna, in pharetra augue nisi et turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec sit amet aliquam sem, ut convallis nisi. Duis feugiat lectus at elit laoreet, in consequat risus dignissim. Nulla posuere sem suscipit, maximus tellus ac, tempor sapien. Donec condimentum dignissim lacus sed rutrum. Suspendisse viverra augue id dignissim tempor.</p>
</section>

app/views/static_pages/contact.html.erb
<section id="contact">
  <div class="col-lg-6 col-md-6" id="map">
    <p>insert map here</p>
  </div> <!-- end map -->
      <div class="col-lg-6 col-md-6" id="deets">
        <div class="header-contact">
          <h1><strong><u>Bikes London</u></strong></h1>
          </div>
        </div> <!-- end header-->
        <div class="body-contact" class="col-lg-12 col-md-12">
          <h5>11 Gloucester Road,London AB56 7GH</h5>
        </div> <!-- end body contact -->
        <br>
        <div class="center-contact" class="col-lg-12 col-md-12">
          <ul class="list-unstyled" id="directory">
            <li><span class="glyphicon glyphicon-phone-alt"></span> mobile +(12)345678910</li>
            <li><span class="glyphicon glyphicon-envelope"></span> email <a href="mailto:abcdef@ghijklm.com?Subject=Enquiry" target="_top"><font color="white"><u>abcdef@ghijklm.com</u></font></a></li>
            <li><span class="glyphicon glyphicon-file"></span> fax +(12)12113114</li>
            <li><span class="glyphicon glyphicon-retweet"></span> twitter<a href="https://twitter.com/pjbasa"><font color="white"><u>@pjbasa</u></font></a></li>
          </ul> <!--end id contacts -->
        </div> <!-- end center contact -->
      </div> <!-- end #contact -->
        <form data-toggle="validator" role="form">
          <div class="row">
            <div id="must" class="col-lg-4 col-md-4">
              <h1><strong><u>Let's Talk!</u></strong></h1>
              <p>*(required fields)</p>
            </div>
          </div>
          <div class="row" id="fields">
            <div class="form-group" class="col-lg-8 col-md-8">
              <label for="inputName" class="control-label">Your Name</label><br>
              <input type="text" class="form-control" id="name" placeholder="John Doe"/>
            </div> <!-- end form group text -->
            <div class="form-group" class="col-lg-8 col-md-8">
              <label for="inputEmail" class="control-label">Your email address*</label><br>
              <input type="email" id="email" class="form-control" placeholder="you@example.com" required/>
              <p id="visible-email"></p>
            </div> <!-- end form-group email -->
            <div class="form-group" class="col-lg-8 col-md-8">
              <label for="tel">Your Contact Number</label>
              <input type="tel" id="tel" class="form-control" placeholder="Complete Phone Number" >
            </div>
          </div>
          <br>
          <div class="row">
            <div class="form-group" class="col-lg-8 col-md-8">
              <label for="inputMessage">Your Message*</label><br>
              <textarea style="resize:none" class="form-control" cols="80" rows="5" placeholder="Leave me a Message!" id="message-box" required></textarea><br>
               <p id="visible-comment"></p>
               <p id="char-count"></p>
              <button type="submit" class="btn btn-default" id="button">Submit</button>
            </div>
          </div> <!-- end row -->
        </form> <!-- end form -->
      </div> <!--end center-contact -->
      <div id="availability-contact" class="col-xs-12 col-md-12 col-lg-12">
        <h3>Available 24/7, 365 days a year (send message or <a href="mailto:abcdef@ghijklm.com?Subject=Enquiry"><font color="white"><u>email</u></font></a> to confirm)</h3>
      </div> <!-- end availability -->
    </section> <!--end contact -->

app/views/static_pages/index.html.erb
<section id="store-front">
  <h1>Welcome to Bikes London</h1>
  <h2>Because cycling is LIFE</h2>
  <p>Welcome! The date and time is <%= Time.now %></p>
</section>

app/views/static_pages/products.html.erb
<section id="products">
  <h2>Products </h2>
  <p> New stock in regularly, feel free to contact us for more info.</p>
  <div class="row">
    <div id="for-sale" align="center">
      <div class="col-md-4 col-lg-4">
        <%=image_tag("red-brompton.jpg", class: "img-responsive")%>
        <p>Brompton</p>
      </div>
      <div class="col-md-4 col-lg-4">
        <%=image_tag("otherbikes.JPG", class: "img-responsive")%>
        <p>Other bikes</p>
      </div>
      <div class="col-md-4 col-lg-4">
        <%=image_tag("dezeen_Folder.jpg", class: "img-responsive")%>
        <p>Dezeen Folder</p>
      </div>
    </div>
  </div>
</section>